package com.example.demo0116.dao;

import com.example.demo0116.domain.Driver;
import com.example.demo0116.domain.DriverExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DriverMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    long countByExample(DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int deleteByExample(DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer driverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int insert(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int insertSelective(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    Driver selectOneByExample(DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    Driver selectOneByExampleSelective(@Param("example") DriverExample example, @Param("selective") Driver.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    List<Driver> selectByExampleSelective(@Param("example") DriverExample example, @Param("selective") Driver.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    List<Driver> selectByExample(DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    Driver selectByPrimaryKeySelective(@Param("driverId") Integer driverId, @Param("selective") Driver.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    Driver selectByPrimaryKey(Integer driverId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Driver record, @Param("example") DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Driver record, @Param("example") DriverExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Driver record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table driver
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Driver record);
}