package com.example.demo0116.dao;

import com.example.demo0116.domain.Locations;
import com.example.demo0116.domain.LocationsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LocationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    long countByExample(LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    int deleteByExample(LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    int insert(Locations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    int insertSelective(Locations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    Locations selectOneByExample(LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    Locations selectOneByExampleSelective(@Param("example") LocationsExample example, @Param("selective") Locations.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    List<Locations> selectByExampleSelective(@Param("example") LocationsExample example, @Param("selective") Locations.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    List<Locations> selectByExample(LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    Locations selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") Locations.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    Locations selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Locations record, @Param("example") LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Locations record, @Param("example") LocationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Locations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table locations
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Locations record);
}