package com.example.demo0116.domain;

import java.util.ArrayList;
import java.util.Arrays;

public class Cars {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.cars_id
     *
     * @mbg.generated
     */
    private Integer carsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.license_number
     *
     * @mbg.generated
     */
    private String licenseNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.model
     *
     * @mbg.generated
     */
    private String model;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.frame_number
     *
     * @mbg.generated
     */
    private String frameNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.driver_id
     *
     * @mbg.generated
     */
    private Integer driverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cars.logdelete
     *
     * @mbg.generated
     */
    private Boolean logdelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.cars_id
     *
     * @return the value of cars.cars_id
     *
     * @mbg.generated
     */
    public Integer getCarsId() {
        return carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.cars_id
     *
     * @param carsId the value for cars.cars_id
     *
     * @mbg.generated
     */
    public void setCarsId(Integer carsId) {
        this.carsId = carsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.license_number
     *
     * @return the value of cars.license_number
     *
     * @mbg.generated
     */
    public String getLicenseNumber() {
        return licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.license_number
     *
     * @param licenseNumber the value for cars.license_number
     *
     * @mbg.generated
     */
    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.model
     *
     * @return the value of cars.model
     *
     * @mbg.generated
     */
    public String getModel() {
        return model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.model
     *
     * @param model the value for cars.model
     *
     * @mbg.generated
     */
    public void setModel(String model) {
        this.model = model;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.frame_number
     *
     * @return the value of cars.frame_number
     *
     * @mbg.generated
     */
    public String getFrameNumber() {
        return frameNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.frame_number
     *
     * @param frameNumber the value for cars.frame_number
     *
     * @mbg.generated
     */
    public void setFrameNumber(String frameNumber) {
        this.frameNumber = frameNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.status
     *
     * @return the value of cars.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.status
     *
     * @param status the value for cars.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.driver_id
     *
     * @return the value of cars.driver_id
     *
     * @mbg.generated
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.driver_id
     *
     * @param driverId the value for cars.driver_id
     *
     * @mbg.generated
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cars.logdelete
     *
     * @return the value of cars.logdelete
     *
     * @mbg.generated
     */
    public Boolean getLogdelete() {
        return logdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cars.logdelete
     *
     * @param logdelete the value for cars.logdelete
     *
     * @mbg.generated
     */
    public void setLogdelete(Boolean logdelete) {
        this.logdelete = logdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", carsId=").append(carsId);
        sb.append(", licenseNumber=").append(licenseNumber);
        sb.append(", model=").append(model);
        sb.append(", frameNumber=").append(frameNumber);
        sb.append(", status=").append(status);
        sb.append(", driverId=").append(driverId);
        sb.append(", logdelete=").append(logdelete);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Cars other = (Cars) that;
        return (this.getCarsId() == null ? other.getCarsId() == null : this.getCarsId().equals(other.getCarsId()))
            && (this.getLicenseNumber() == null ? other.getLicenseNumber() == null : this.getLicenseNumber().equals(other.getLicenseNumber()))
            && (this.getModel() == null ? other.getModel() == null : this.getModel().equals(other.getModel()))
            && (this.getFrameNumber() == null ? other.getFrameNumber() == null : this.getFrameNumber().equals(other.getFrameNumber()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getDriverId() == null ? other.getDriverId() == null : this.getDriverId().equals(other.getDriverId()))
            && (this.getLogdelete() == null ? other.getLogdelete() == null : this.getLogdelete().equals(other.getLogdelete()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cars
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCarsId() == null) ? 0 : getCarsId().hashCode());
        result = prime * result + ((getLicenseNumber() == null) ? 0 : getLicenseNumber().hashCode());
        result = prime * result + ((getModel() == null) ? 0 : getModel().hashCode());
        result = prime * result + ((getFrameNumber() == null) ? 0 : getFrameNumber().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getDriverId() == null) ? 0 : getDriverId().hashCode());
        result = prime * result + ((getLogdelete() == null) ? 0 : getLogdelete().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table cars
     *
     * @mbg.generated
     */
    public enum Column {
        carsId("cars_id", "carsId", "INTEGER", false),
        licenseNumber("license_number", "licenseNumber", "VARCHAR", false),
        model("model", "model", "VARCHAR", false),
        frameNumber("frame_number", "frameNumber", "VARCHAR", false),
        status("status", "status", "INTEGER", true),
        driverId("driver_id", "driverId", "INTEGER", false),
        logdelete("logdelete", "logdelete", "BIT", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cars
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cars
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cars
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cars
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cars
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table cars
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table cars
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}