package com.example.demo0116.domain;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Arrays;

public class Location {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.location_id
     *
     * @mbg.generated
     */
    private Integer locationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.start_longitude
     *
     * @mbg.generated
     */
    private BigDecimal startLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.start_latitude
     *
     * @mbg.generated
     */
    private BigDecimal startLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.desination_longitude
     *
     * @mbg.generated
     */
    private BigDecimal desinationLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.destination_latitude
     *
     * @mbg.generated
     */
    private BigDecimal destinationLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.order_id
     *
     * @mbg.generated
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column location.route
     *
     * @mbg.generated
     */
    private String route;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.location_id
     *
     * @return the value of location.location_id
     *
     * @mbg.generated
     */
    public Integer getLocationId() {
        return locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.location_id
     *
     * @param locationId the value for location.location_id
     *
     * @mbg.generated
     */
    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.start_longitude
     *
     * @return the value of location.start_longitude
     *
     * @mbg.generated
     */
    public BigDecimal getStartLongitude() {
        return startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.start_longitude
     *
     * @param startLongitude the value for location.start_longitude
     *
     * @mbg.generated
     */
    public void setStartLongitude(BigDecimal startLongitude) {
        this.startLongitude = startLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.start_latitude
     *
     * @return the value of location.start_latitude
     *
     * @mbg.generated
     */
    public BigDecimal getStartLatitude() {
        return startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.start_latitude
     *
     * @param startLatitude the value for location.start_latitude
     *
     * @mbg.generated
     */
    public void setStartLatitude(BigDecimal startLatitude) {
        this.startLatitude = startLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.desination_longitude
     *
     * @return the value of location.desination_longitude
     *
     * @mbg.generated
     */
    public BigDecimal getDesinationLongitude() {
        return desinationLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.desination_longitude
     *
     * @param desinationLongitude the value for location.desination_longitude
     *
     * @mbg.generated
     */
    public void setDesinationLongitude(BigDecimal desinationLongitude) {
        this.desinationLongitude = desinationLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.destination_latitude
     *
     * @return the value of location.destination_latitude
     *
     * @mbg.generated
     */
    public BigDecimal getDestinationLatitude() {
        return destinationLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.destination_latitude
     *
     * @param destinationLatitude the value for location.destination_latitude
     *
     * @mbg.generated
     */
    public void setDestinationLatitude(BigDecimal destinationLatitude) {
        this.destinationLatitude = destinationLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.order_id
     *
     * @return the value of location.order_id
     *
     * @mbg.generated
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.order_id
     *
     * @param orderId the value for location.order_id
     *
     * @mbg.generated
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column location.route
     *
     * @return the value of location.route
     *
     * @mbg.generated
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column location.route
     *
     * @param route the value for location.route
     *
     * @mbg.generated
     */
    public void setRoute(String route) {
        this.route = route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", locationId=").append(locationId);
        sb.append(", startLongitude=").append(startLongitude);
        sb.append(", startLatitude=").append(startLatitude);
        sb.append(", desinationLongitude=").append(desinationLongitude);
        sb.append(", destinationLatitude=").append(destinationLatitude);
        sb.append(", orderId=").append(orderId);
        sb.append(", route=").append(route);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Location other = (Location) that;
        return (this.getLocationId() == null ? other.getLocationId() == null : this.getLocationId().equals(other.getLocationId()))
            && (this.getStartLongitude() == null ? other.getStartLongitude() == null : this.getStartLongitude().equals(other.getStartLongitude()))
            && (this.getStartLatitude() == null ? other.getStartLatitude() == null : this.getStartLatitude().equals(other.getStartLatitude()))
            && (this.getDesinationLongitude() == null ? other.getDesinationLongitude() == null : this.getDesinationLongitude().equals(other.getDesinationLongitude()))
            && (this.getDestinationLatitude() == null ? other.getDestinationLatitude() == null : this.getDestinationLatitude().equals(other.getDestinationLatitude()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getRoute() == null ? other.getRoute() == null : this.getRoute().equals(other.getRoute()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table location
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getLocationId() == null) ? 0 : getLocationId().hashCode());
        result = prime * result + ((getStartLongitude() == null) ? 0 : getStartLongitude().hashCode());
        result = prime * result + ((getStartLatitude() == null) ? 0 : getStartLatitude().hashCode());
        result = prime * result + ((getDesinationLongitude() == null) ? 0 : getDesinationLongitude().hashCode());
        result = prime * result + ((getDestinationLatitude() == null) ? 0 : getDestinationLatitude().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getRoute() == null) ? 0 : getRoute().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table location
     *
     * @mbg.generated
     */
    public enum Column {
        locationId("location_id", "locationId", "INTEGER", false),
        startLongitude("start_longitude", "startLongitude", "DECIMAL", false),
        startLatitude("start_latitude", "startLatitude", "DECIMAL", false),
        desinationLongitude("desination_longitude", "desinationLongitude", "DECIMAL", false),
        destinationLatitude("destination_latitude", "destinationLatitude", "DECIMAL", false),
        orderId("order_id", "orderId", "INTEGER", false),
        route("route", "route", "LONGVARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table location
         *
         * @mbg.generated
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table location
         *
         * @mbg.generated
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table location
         *
         * @mbg.generated
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table location
         *
         * @mbg.generated
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table location
         *
         * @mbg.generated
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table location
         *
         * @mbg.generated
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table location
         *
         * @mbg.generated
         */
        public String getAliasedEscapedColumnName() {
            return this.getEscapedColumnName();
        }
    }
}